create table if not exists customer_trace_segments(
segment_identifier Integer not null,
corp_entity Integer null,
channel_finance varchar(255) null,
supply_chain_finance varchar(255) null,
obj_finance varchar(255) null,
commodity_finance varchar(255) null,
project_finance char null,
income_real_estate varchar(255) null,
qualifying_development varchar(255) null,
central_institute varchar(255) null,
soverign_bonds varchar(255) null,
regional_authority varchar(255) null,
public_service_entity varchar(255) null,
non_bank_org varchar(255) null,
central_counter_party varchar(255) null,
other_developmentals varchar(255) null,
ipre_characteristics Integer null,
administrative_entities varchar(255) null,
entity_state varchar(255) null,
remarks varchar(255) null,
constraint customer_trace_segments_pk primary key(segment_identifier)); 